#!/usr/bin/env python3
"""Generate the Android 13 Codec2 framework used by the stock codec blobs.

The MediaTek and Dolby Codec2 services and plugins were built against the
Android 13 Codec2 framework (libcodec2*, libsfplugin_ccodec_utils,
libstagefright_foundation, ...). The Android 16 source builds of those
libraries have a different C++ ABI, so the stock components fail (null
interfaces, crashes in listComponents). This copies the stock/VNDK 33
libraries, renames them with a -v33 suffix and relinks them among themselves.
The codec blobs are pointed at the renamed names by extract-files.py.

Usage: generate.py <stock vendor dump> (e.g. .../354/super/vendor)
"""
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOP = os.path.abspath(os.path.join(HERE, '../../../../..'))
PATCHELF = os.path.join(TOP, 'prebuilts/extract-tools/linux-x86/bin/patchelf-0_17_2')
VNDK33 = os.path.join(TOP, 'prebuilts/vndk/v33/arm64/arch-arm64-armv8-a/shared/vndk-core')

# name -> source ('stock' vendor/lib64 or 'vndk33')
LIBS = {
    'libcodec2': 'vndk33',
    # Provided by hardware/lineage/compat (same -v33 soname); relink only.
    'libstagefright_foundation': 'lineage',
    'libstagefright_bufferqueue_helper': 'vndk33',
    # GraphicBuffer is constructed inline by libcodec2_vndk; its layout changed.
    'libui': 'vndk33',
    'libcodec2_vndk': 'stock',
    'libcodec2_soft_common': 'stock',
    'libsfplugin_ccodec_utils': 'stock',
    'libcodec2_hidl@1.0': 'stock',
    'libcodec2_hidl@1.1': 'stock',
    'libcodec2_hidl@1.2': 'stock',
    'libcodec2_hidl_plugin': 'stock',
    'libstagefright_bufferpool@2.0.1': 'stock',
}


def renamed(lib):
    return f'{lib}-v33'


def needed(path):
    out = subprocess.run([PATCHELF, '--print-needed', path], capture_output=True, text=True,
                         check=True).stdout
    return out.split()


def main():
    stock = sys.argv[1]
    prebuilt_dir = os.path.join(HERE, 'lib64')
    os.makedirs(prebuilt_dir, exist_ok=True)
    for lib, origin in LIBS.items():
        if origin == 'lineage':
            continue
        src = (os.path.join(VNDK33, f'{lib}.so') if origin == 'vndk33'
               else os.path.join(stock, 'lib64', f'{lib}.so'))
        dst = os.path.join(prebuilt_dir, f'{renamed(lib)}.so')
        shutil.copyfile(src, dst)
        subprocess.run([PATCHELF, '--set-soname', f'{renamed(lib)}.so', dst], check=True)
        if lib.startswith('libcodec2_hidl@'):
            # Android 13 libbase string overloads (compat/libbase).
            subprocess.run([PATCHELF, '--add-needed', 'libbase_sycamore_shim.so', dst], check=True)
        for dep in needed(dst):
            base = dep[:-3]
            if base in LIBS:
                subprocess.run([PATCHELF, '--replace-needed', dep, f'{renamed(base)}.so', dst],
                               check=True)

    with open(os.path.join(HERE, 'Android.bp'), 'w') as bp:
        bp.write('// Generated by generate.py; see that file for details.\n')
        for lib in (l for l, o in LIBS.items() if o != 'lineage'):
            bp.write(f'''
cc_prebuilt_library_shared {{
    name: "{renamed(lib)}",
    vendor: true,
    compile_multilib: "64",
    srcs: ["lib64/{renamed(lib)}.so"],
    check_elf_files: false,
    strip: {{ none: true }},
}}
''')
    print('\n'.join(f'{renamed(lib)}.so' for lib in LIBS))


if __name__ == '__main__':
    main()
